config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'things#index'
  resources :things do
    resources :comments, only: :create
    collection do
      get 'search'
      get 'things_search'
    end
  end
  resources :users
end

app/models/thing.rb
class Thing < ApplicationRecord

  # with_options presence: true do
  #   validates :image
  #   validates :name
  #   validates :explanation
  #   validates :price
  #   validates :score
  #   validates :date
  # end

  belongs_to :user
  has_one_attached :image
  has_many :comments
  has_many :thing_tag_relations
  has_many :tags, through: :thing_tag_relations

  def self.search(search)
    if search != ""
      Thing.where('name LIKE(?) OR explanation LIKE(?)', "%#{search}%", "%#{search}%")
    else
      Thing.all
    end
  end

end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:edit, :show, :destroy]
  before_action :move_to_sign_in, except: [:index, :show, :search, :things_search]

  def index
    @things = Thing.includes(:user).order('created_at DESC')
  end

  def new
    @thing = ThingTag.new
  end

  def create
    @thing =  ThingTag.new(thing_params)
    if @thing.save
      redirect_to root_path(@thing)
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @thing.comments.includes(:user).order('created_at DESC')
    @tagid = ThingTagRelation.find_by(thing_id: @thing.id)
    @tag = Tag.find_by(id: @tagid.tag_id)
  end

  def destroy
    @tagid = ThingTagRelation.find_by(thing_id: @thing.id)
    @tagid.destroy
    @thing.destroy
    redirect_to root_path
  end

  def edit
    @things = ThingTag.new
    @thing = Thing.find(params[:id])
  end

  def update
    @thing =  ThingTag.new(thing_params)
    @thing.thing_id = params[:id]
    if @thing.update(thing_params)
      redirect_to root_path(@thing)
    else
      redirect_to edit_thing_path(params[:id])
    end
  end

  def search
    return nil if params[:input] == ''
    tag = Tag.where(['tagname LIKE ?', "%#{params[:input]}%"])
    render json: { keyword: tag }
  end

  def things_search
    @things = Thing.search(params[:keyword]).includes(:user).order('created_at DESC')
  end

  private

  def move_to_sign_in
    redirect_to user_session_path unless user_signed_in?
  end

  def thing_params
    params.require(:thing_tag).permit(:name, :explanation, :score, :date, :price, :tagname, :image).merge(user_id: current_user.id)
  end

  def set_thing
    @thing = Thing.find(params[:id])
  end

end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/edit.html.erb
<%= render "shared/header" %>
<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">編集</h2>
    <%= form_with model: @things, url: thing_path, method: :put, local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <% render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品中画像
      </div>
        <%= image_tag @thing.image, class: 'image', width:600 %>
    </div>
    <%# /出品画像 %>
    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像の変更
      </div>
      <div id="image-list"></div>
      <div class="click-upload">
        <p>
          クリックして画像を変更
        </p>
        <%= f.file_field :image, id:"thing-image", value:@thing.image %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        名前
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"form-control", id:"thing-name", value:@thing.name, placeholder:"お気に入りの物の名前を教えて下さい！（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          紹介
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explanation, class:"items-text", id:"thing-info", value:@thing.explanation, placeholder:"お気に入りの物の紹介（必須 1,000文字まで）どうしてお気に入りなのか、思い出や便利な点などを教えてください！" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          タグ
        </div>
        <%= f.text_field :tagname, class:"items-text", id:"tag-field", value:@thing.tags[0].tagname, placeholder:"タグをつけることが出来ます。" %>
      </div>
      <div id="search-result">
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          価格
          <span class="indispensable">必須(半角数字)</span>
        </div>
      <%= f.text_field :price, class:"items-text", id:"thing-name", value:@thing.price, placeholder:"貰い物や価格がわからないものは0円にしましょう！", maxlength:"40" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          お気に入り度
          <span class="indispensable">必須(半角数字)</span>
        </div>
      <%= f.text_field :score, class:"items-text", id:"thing-name", value:@thing.score, placeholder:"どのくらいお気に入りか0-100で点数をつけてみましょう！", maxlength:"3" %>
      </div>
        <div class="items-explain">
    <div class='form-text-wrap'>
      <label class="form-text">出会った日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :date,
                    class:'select-birth',
                    id:"birth-date",
                    default: @thing.date,
                    use_month_numbers: true,
                    # prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 0),
                    # discard_day:true,
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', thing_path(@thing.id), class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>
<%= render "shared/footer" %>

app/views/things/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      My Favorite Things
    </h2>
    <p class='service-explain'>
      〜私のお気に入り〜
    </p>
  </div>
  <%# //帯部分  %>


  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>みんなのお気に入り一覧</h2>
    <%= link_to 'あなたも投稿してみよう！', new_thing_path, class: "subtitle" %>
    <ul class='item-lists'>

    <% @things.each do |thing| %>
      <li class='list'>
        <%= link_to thing_path(thing.id) do %>
        <div class='item-img-content'>
          <%= image_tag thing.image, class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= thing.name %>
          </h3>
          <div class='item-price'>
            <span><%= thing.price.to_s(:delimited) %>円<br></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'><%= thing.score %></span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
    <% end %>

      <%# 商品がない場合のダミー %>
      <% unless @things.present? %>
        <li class='list'>
          <%= link_to '#' do %>
          <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "item-img" %>
          <div class='item-info'>
            <h3 class='item-name'>
              商品を出品してね！
            </h3>
            <div class='item-price'>
              <span>99999999円<br>(税込み)</span>
              <div class='star-btn'>
                <%= image_tag "star.png", class:"star-icon" %>
                <span class='star-count'>0</span>
              </div>
            </div>
          </div>
          <% end %>
        </li>
      <% end %>
      <%# //商品がない場合のダミー %>
    </ul>
  </div>
  <%# //商品一覧 %>

</div>
<%= link_to new_thing_path do %>
  <div class='purchase-btn'>
    <span class='purchase-btn-text'>新規投稿</span>
    <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  </div>
<% end %>
<%= render "shared/footer" %>

app/views/things/new.html.erb
<%= render "shared/header" %>
<div class="items-sell-contents">

  <div class="items-sell-main">
    <h2 class="items-sell-title">お気に入りを投稿しよう！</h2>
    <%= form_with model: @thing, url: things_path, local: true do |f| %>

    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div id="image-list"></div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"thing-image" %>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        名前
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"form-control", id:"thing-name", placeholder:"お気に入りの物の名前を教えて下さい！（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          紹介
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explanation, class:"items-text", id:"thing-info", placeholder:"お気に入りの物の紹介（必須 1,000文字まで）どうしてお気に入りなのか、思い出や便利な点などを教えてください！" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          タグ
        </div>
        <%= f.text_field :tagname, class:"items-text", id:"tag-field", placeholder:"タグをつけることが出来ます。" %>
      </div>
      <div id="search-result">
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          価格
          <span class="indispensable">必須(半角数字)</span>
        </div>
      <%= f.text_field :price, class:"items-text", id:"thing-name", placeholder:"貰い物や価格がわからないものは0円にしましょう！", maxlength:"40" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          お気に入り度
          <span class="indispensable">必須(半角数字)</span>
        </div>
      <%= f.text_field :score, class:"items-text", id:"thing-name", placeholder:"どのくらいお気に入りか0-100で点数をつけてみましょう！", maxlength:"3" %>
      </div>
        <div class="items-explain">
    <div class='form-text-wrap'>
      <label class="form-text">出会った日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :date,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    # prompt:'--',
                    default: Date.new(2020, 1, 1), # 最初に表示されている年月日
                    start_year: 1930,
                    end_year: (Time.now.year - 0),
                    # discard_day:true,
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>
    </div>
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>
<%= render "shared/footer" %>

app/views/things/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h1 class="name">
    <a href="/users/<%= @thing.user.id %>"><%= @thing.user.nickname %>さんのお気に入り</a>
      <%#= @thing.name %>
    </h1>
    <div class='item-img-content'>
      <%= image_tag @thing.image ,class:"item-box-img" %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%= @thing.name %>
      </span>
    </div>

    <div class="item-explain-box">
      <span><%= @thing.explanation %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">リンク</th>
          <td class="detail-value"><a href="/users/<%= @thing.user.id %>"><%= @thing.user.nickname %>さんのマイページ</a></td>
        </tr>
        <tr>
          <th class="detail-item">価格</th>
          <td class="detail-value"><%= @thing.price.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th class="detail-item">お気に入り度</th>
          <td class="detail-value"><%= @thing.score %></td>
        </tr>
        <tr>
          <th class="detail-item">出会った時期</th>
          <td class="detail-value"><%= @thing.date %></td>
        </tr>
        <tr>
          <th class="detail-item">タグ</th>
          <td class="detail-value"><%= @tag.tagname %></td>
        </tr>
      </tbody>
    </table>
    <br><br>
    <% if user_signed_in? && current_user.id == @thing.user_id %>
      <%= link_to '商品の編集', edit_thing_path, method: :get, class: "item-red-btn" %>
      <p class='or-text'>or</p>
      <%= link_to '削除', thing_path, method: :delete, class:'item-destroy' %>
    <% end %>
  </div>
  <div class="comment-box">
    <% if user_signed_in? %>
      <%= form_with url: thing_comments_path(@thing.id), model: @comment, local: true do |f| %>
        <%= f.text_area :text, class:"comment-text", placeholder:"コメントをご記入ください！" ,rows:"7" ,maxlength:"1000" %>
        <p class="comment-warn">
          <br>
        </p>
        <%= f.button type = "submit" , class:"comment-btn" do %>
          <%= image_tag "comment.png" , class:"comment-flag-icon" ,width:"20",height:"25"%>
          <span>コメントする<span>
        <% end %>
      <% end %>
    <% else %>
      <p class="comment-warn">
        <br>
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" , class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>ログインしてコメントしよう<span>
      </button>
    <% end %>

      <div class="container">
        <h3>＜コメント一覧＞</h3>
        <div id="comments" class="comments">
          <% if @comments %>
            <% @comments.each do |comment| %>
              <% if user_signed_in? && current_user.id == comment.user_id %>
                <p>
                  <%= comment.text %>
                  <strong> ：<%= comment.user.nickname %></strong>
                </p>
              <% else %>
                <p>
                  <strong><%= comment.user.nickname %>： </strong>
                  <%= comment.text %>
                </p>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/things/things_search.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      My Favorite Things
    </h2>
    <p class='service-explain'>
      〜私のお気に入り〜
    </p>
    <p class='service-explain'>
      
    </p>

  </div>
  <%# //画面上部の「人生を変えるフリマアプリ」帯部分  %>


  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>「<%=params[:keyword]%>」の検索結果</h2>
    <%= link_to '新規投稿する', new_thing_path, class: "subtitle" %>
    <ul class='item-lists'>

    <% @things.each do |thing| %>
      <li class='list'>
        <%= link_to thing_path(thing.id) do %>
        <div class='item-img-content'>
          <%= image_tag thing.image, class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= thing.name %>
          </h3>
          <div class='item-price'>
            <span><%= thing.price %>円<br></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'><%= thing.score %></span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
    <% end %>

    </ul>
  </div>
  <%# //商品一覧 %>

</div>
<%= link_to new_thing_path do %>
  <div class='purchase-btn'>
    <span class='purchase-btn-text'>出品する</span>
    <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  </div>
<% end %>
<%= render "shared/footer" %>