config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'things#index'
  resources :things do
    resources :comments, only: :create
    collection do
      get 'search'
      get 'things_search'
    end
  end
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :gender

  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]


  VALID_email_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i.freeze
  VALID_password_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,100}\z/i.freeze

  with_options presence: true do
    validates :nickname
    validates :email, format: { with: VALID_email_REGEX }
    # validates :password, format: { with: VALID_password_REGEX }
    validates :birthday
    validates :gender_id, numericality: { other_than: 1 } 
  end


  has_many :things
  has_many :comments
  has_many :sns_credentials

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create

    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def google_oauth2
    authorization
  end
  
  private
  
  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end  end
  
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @user = User.find(params[:id])
    @things = user.things
  end


  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      sign_in(@user)
      redirect_to root_path and return
    else
      render :edit and return 
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :nickname, :birthday)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/header" %>
<%= form_with class: 'registration-main', model: @user , url: user_path(current_user.id), method: :patch, local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      会員情報入力
    </h1>
  </div>


  <div class='login-flash-message'>
    <%= flash[:notice] %>
    <%= flash[:alert] %>
  </div>


  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) myfavoritethings太郎", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>

  <%if @sns_id.present? %>
    <%= hidden_field_tag :sns_auth, true %>
  <% else %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password, class:"input-default", id:"password", placeholder:"パスワード" %>
    <p class='info-text'>※変更する場合は新しいパスワードを入力してください（6文字以上の半角英数字で、英字と数字の両方を含めて設定してください）</p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード(確認)</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password_confirmation, class:"input-default", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
  </div>

  <% end %>

    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">性別</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"select-box"}) %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <p class='info-text'>※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。</p>
  </div>
  <div class="form-group">
    <h2 class='form-bottom-text'>
      「会員登録」のボタンを押すことにより、
      <span>利用規約</span>
      <br>に同意したものとみなします
    </h2>
  </div>
  <div class='register-btn'>
    <%= f.submit "変更" ,class:"register-red-btn" %>
  </div>
  <p class='register-info'>本人情報の登録について</p>
</div>
<% end %>
<%= render "shared/footer"%>

app/views/users/show.html.erb
<%= render "shared/header" %>

<%= form_with class: 'registration-main', model: @user , url: edit_user_path(@user.id), method: :get, local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      <%= @user.nickname %>さんのマイページ
    </h1>
  </div>
            <% if user_signed_in? && current_user.id == @user.id %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
    </div>
    <div class='input-name-wrap'>
      <h1><%= @user.nickname %></h1>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
    </div>
    <div class='input-name-wrap'>
      <h1><%= @user.email %></h1>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
    </div>
    <div class='input-name-wrap'>
      <h1><%= @user.birthday %></h1>
    </div>
  </div>

  <div class="form-group">
  </div>

  <div class="form-group">
  </div>

  <div class='register-btn'>
    <%= f.submit "会員情報の編集" ,class:"register-red-btn" %>
  </div>
          <% end %>

  <div class='form-header'>
    <h3 class='form-header-text'>
      お気に入り一覧
    </h3>
  </div>

    <div class="card-deck">
      <% @things.each do |thing| %>

        <div class="card">
          <div class="card-body">
            <p class="card-text"><%= thing.name %></p>
          </div>
                        <%= link_to thing_path(thing.id) do %>
          <%= image_tag thing.image ,class:"item-box-img2 w-100", alt:"Card image" %>
                      <% end %>
          <div class="card-body">
            <p class="card-text"><%= thing.explanation %></p>
          </div>
        </div>
      <% end %>
    </div>



</div>


<% end %>



<%= render "shared/footer"%>