config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'things#index'
  resources :things do
    resources :comments, only: :create
    collection do
      get 'search'
      get 'things_search'
    end
  end
  resources :users
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>

  <%= link_to image_tag("myfavoritethings-logo-white.png", class:"logo-white"), "#" %>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>

    <h1>
        <a href="/">MyFavoriteThings</a>
    </h1>
    <nav class="pc-nav">
        <ul>
            <li>
              <%= form_with(url: things_search_things_path, local: true, method: :get, class: "search-form") do |form| %>
                <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "input-box" %>
                <% form.submit "検索", class: "search-btn" %>
                <button class="search-button">
                  <%= image_tag "search.png", class:"search-icon" %>
                </button>
              <% end %>
            </li>
            <% if user_signed_in? %>
              <li><%= link_to "MYPAGE", user_path(current_user), class: "user-nickname-1"  %></li>
              <li><%= link_to 'LOGOUT', destroy_user_session_path, method: :delete, class: "logout-1" %></li> 
            <% else %>
              <li><%= link_to 'LOGIN', new_user_session_path, class: "login-1" %></li>
              <li><%= link_to 'SIGNUP', new_user_registration_path, class: "sign-up-1" %></li>
            <% end %>
        </ul>
    </nav>

</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>myfavoritethings利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "myfavoritethings-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%#= link_to image_tag("myfavoritethings-logo-color.png", class:"second-logo"), "/" %>
</header>